name: bionify
description: >-
  Bionify easy reading. By adding a bold prefix it simplify the eye guidance 
  making any fast reading much comfortable.
version: 0.0.1+6
homepage: https://github.com/Solido/flutter-bionify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

screenshots:
  - description: 'Compare basic text with bionify.'
    path: example/screenshots/comparaison.png
