name: bionify
description: Bionify easy reading
version: 0.0.1+2
homepage: https://github.com/Solido/flutter-bionify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

screenshots:
  - description: 'Compare basic text with bionify.'
    path: example/screenshots/comparaison.png